### PR TITLE
Add support for the reservation system

### PR DESCRIPTION
**Pull request by triceo**
There are two regimes. In the first regime, the app only confirms reservations that match the existing strategy. In the second regime, the app also registers for every available queue, overriding any settings that the user may have previously kept.

This is a backwards incompatible change, requiring addition of some information into the existing strategies.

### CODE REVIEW

**Comment by triceo** [comment]
FYI @jhrcek This brings the final changes to the strategy for 5.1.

**Comment by jhrcek** [comment]
@triceo Ok, I think I understand the changes required in the config tool:
I should add a dropdown/radio with those 3 possibilities into "Obecná nastavení".
Which of the 3 possibilities would you like to be selected by default?

**Comment by triceo** [comment]
@jhrcek Correct. By default, we should probably just select the one that disables the system entirely.

**Comment by jhrcek** [comment]
Ok, going to implement it, but I'm afraid that the difference between
"Robot má pravidelně kontrolovat ..." and 
"Robot má převzít kontrolu .." is not self-explanatory enough and will require additional popover with explanation. Let's clarify this in person tomorrow..

**Pull request merged**
